version: '2'

networks:
  db-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  mysql:
    container_name: user-mysql
    image: mysql:oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      db-net:
        ipv4_address: 172.19.0.2
        aliases:
          - user-mysql

  mongo:
    container_name: user-mongo
    image: mongo
    ports:
      - "27000:27000"
    networks:
      db-net:
        ipv4_address: 172.19.0.3
        aliases:
          - user-mongo




